### ISSUE TITLE
Doesn't download .png images

### ISSUE THREAD

**Issue by ssamachi** [Nylonicious/naver-post-downloader#1]
I don't know if this is actually a problem but I encountered this problem while trying to download in this link. https://m.post.naver.com/viewer/postView.naver?volumeNo=30144251

I tried using this code already and when I check all images that I was able to download before wall all in .jpg format. I think it doesn't work downloading .png images

**Comment by nylonicious** [comment]
After closer inspection, all the images on the page are in `jpeg` format. And running script with your url downloaded all the pictures from the post.
